In [1]:
import pandas as pd
import csv
import seaborn as sns
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import plotly.graph_objects as go
import plotly.express as px
import numpy as np

Linux

In [11]:
data = pd.read_csv('/home/max/stayahead/analysis/datasets/AF_1step_pred_wuhan_v1_b2b_sorted.csv')
# data = pd.read_csv('/home/max/stayahead/analysis/datasets/predictions/pred_ref/ESM_1step_pred_epc_15-06.csv')
df_desc = pd.read_csv('/home/max/stayahead/analysis/AF_1step_pred_wuhan_v1_b2b_descriptive_stats.csv')
df_ref = pd.read_csv('/home/max/stayahead/analysis/datasets/references/alphafold/controls_metrics.csv')
df_var = pd.read_csv('/home/max/stayahead/analysis/datasets/predictions/variants/AF_variants.csv')

MAC

In [ ]:
data = pd.read_csv('/Users/maxvandenboom/stayahead/analysis/AF_1step_pred_wuhan_v1_b2b_sorted.csv')
df_desc = pd.read_csv('/Users/maxvandenboom/stayahead/analysis/AF_1step_pred_wuhan_v1_b2b_descriptive_stats.csv')
df_var = pd.read_csv('/Users/maxvandenboom/stayahead/analysis/datasets/predictions/variants/AF_variants.csv')
df_ref = pd.read_csv('/Users/maxvandenboom/stayahead/analysis/datasets/references/alphafold/controls_metrics.csv')

Complexity

In [3]:
#AF
df_5_bits = pd.read_csv('/home/max/stayahead/analysis/datasets/complexity/AF/AF_1step_pred_wuhan_v1_b2b_5_Bits.csv')
df_16_bits = pd.read_csv('/home/max/stayahead/analysis/datasets/complexity/AF/AF_1step_pred_wuhan_v1_b2b_16_Bits.csv')
df_1h_6_bits = pd.read_csv('/home/max/stayahead/analysis/datasets/complexity/AF/AF_1step_pred_wuhan_v1_b2b_1_Hot_6_Bits.csv')
df_1h_20_bits = pd.read_csv('/home/max/stayahead/analysis/datasets/complexity/AF/AF_1step_pred_wuhan_v1_b2b_1_Hot_20_Bits.csv')

In [7]:
data.head()

,seq_id,wildtype,site,mutation,rmsd,tm_score,sasa,avg_hydro,total_hydro,plddt,...,ppII,sheet,sidechain,bind,delta_bind,expr,delta_expr,confidence_bind,confidence_expr,mutation_site
0,T1A,T,1,A,3.997568,0.987932,10110.870340,-0.237868,-0.210769,93.834862,...,0.078990,0.370241,0.575133,8.70879,-0.02454,10.01110,-0.17363,-0.788544,-1.079032,A1
1,N2A,N,2,A,3.983886,0.987907,10130.180033,-0.231746,-0.196410,94.053084,...,0.078692,0.372887,0.575646,8.78958,0.01797,9.67349,-0.51239,0.072748,0.070400,A2
2,L3A,L,3,A,5.528765,0.987433,10089.973807,-0.244293,-0.233846,94.082982,...,0.079656,0.372000,0.574959,8.81095,0.03934,10.23607,0.05019,0.072992,0.070893,A3
3,C4A,C,4,A,2.555380,0.987544,10162.141786,-0.241875,-0.227179,93.877816,...,0.079364,0.370590,0.573995,7.90036,-0.87125,8.95448,-1.23139,0.072667,0.070400,A4
4,P5A,P,5,A,3.958153,0.987820,10170.901038,-0.226909,-0.206154,93.887746,...,0.077133,0.372390,0.576215,8.66949,-0.10211,10.11112,-0.07476,0.075023,0.072494,A5

In [24]:
# Selecting only numeric columns
numeric_df = data.select_dtypes(include=['float64', 'int64'])

# Setting up the subplot grid
num_columns = numeric_df.shape[1]
num_rows = (num_columns // 3) + 1

fig, axes = plt.subplots(num_rows, 3, figsize=(20, 5 * num_rows))
axes = axes.flatten()

# Calculate the maximum y-value for the y-axis across all KDE plots
max_y = 0
for column in numeric_df.columns:
    kde = sns.kdeplot(numeric_df[column])
    current_max_y = max([line.get_ydata().max() for line in kde.get_lines()])
    max_y = max(max_y, current_max_y)
    plt.close()  # Close the temporary plot to avoid displaying it

# Plotting KDE for each numerical column with a consistent y-axis scale
for i, column in enumerate(numeric_df.columns):
    sns.kdeplot(numeric_df[column], ax=axes[i], fill=True)
    axes[i].set_title(column)
    axes[i].set_ylim(0, max_y)

# Remove any empty subplots
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

# Adjust layout
plt.tight_layout()
plt.show()

In [ ]:
# Creating a violin plot for all numerical columns
plt.figure(figsize=(15, 10))
sns.violinplot(data=df_desc, inner="quartile")
plt.xticks(rotation=90)
plt.title('Violin Plot of Numerical Columns')
plt.show()

Density Plot; kde

In [32]:
columns_list = data.columns.tolist()

In [34]:
c_list = ['rmsd', 'tm_score', 'sasa', 'avg_hydro', 'plddt', 'local_net_energy']

In [43]:
c_list = [
 'local_net_energy',
 'iptm_ptm',
 'iptm',
 'pDockQ/mpDockQ',
 'average_interface_pae',
 'average_interface_plddt',
 'binding_energy',
 'Num_intf_residues',
 'Polar',
 'Hydrophobhic',
 'Charged',
 'contact_pairs',
 'sc',
 'hb',
 'sb',
 'int_solv_en',
 'int_area',
 'pi_score',
]

In [41]:
# data = data.dropna()
data['pi_score'] = pd.to_numeric(data['pi_score'])
df_var['pi_score'] = pd.to_numeric(df_var['pi_score'])
df_ref['pi_score'] = pd.to_numeric(df_ref['pi_score'])
df_ref['binding_energy'] = pd.to_numeric(df_ref['binding_energy'])

In [44]:
# column_to_normalize = 'local_net_energy'
for column_to_normalize in c_list:
    print(column_to_normalize)
    min = data[column_to_normalize].min()
    max = data[column_to_normalize].max()
    data[column_to_normalize] = (data[column_to_normalize] - min) / (max - min)
    df_var[column_to_normalize] = (df_var[column_to_normalize] - min) / (max - min)
    df_ref[column_to_normalize] = (df_ref[column_to_normalize] - min) / (max - min)

local_net_energy
iptm_ptm
iptm
pDockQ/mpDockQ
average_interface_pae
average_interface_plddt
binding_energy
Num_intf_residues
Polar
Hydrophobhic
Charged
contact_pairs
sc
hb
sb
int_solv_en
int_area
pi_score

In [39]:
data

,seq_id,wildtype,site,mutation,rmsd,tm_score,sasa,avg_hydro,total_hydro,plddt,local_net_energy,global_net_energy
0,G72R,G,72,R,0.652440,0.389291,18593.003567,-0.261451,-0.244615,23.136774,174134.567240,174134.567240
1,D73L,D,73,L,0.649924,0.452471,16551.722910,-0.201134,-0.186154,23.600130,158378.794682,158378.794682
2,D73P,D,73,P,0.624286,0.473718,16666.825161,-0.229705,-0.213846,23.638132,179512.756284,179512.756284
3,E74H,E,74,H,0.644878,0.465446,16805.735473,-0.238171,-0.222051,23.314119,193044.249824,193044.249824
4,E74P,E,74,P,0.564487,0.479605,17045.420919,-0.229705,-0.213846,23.933160,171998.262787,171998.262787
...,...,...,...,...,...,...,...,...,...,...,...,...
3700,D110V,D,110,V,0.152480,0.744464,18173.109021,-0.199017,-0.184103,22.900778,201579.909683,201579.909683
3701,S111D,S,111,D,0.563108,0.511268,17805.102142,-0.254044,-0.237436,23.438835,201018.276544,201018.276544
3702,S111H,S,111,H,0.593476,0.381628,19130.631054,-0.252457,-0.235897,22.797673,188047.682996,188047.682996
3703,D110A,D,110,A,0.532285,0.535861,18270.715202,-0.211716,-0.196410,22.609091,170532.828174,170532.828174
3704,D110S,D,110,S,0.522264,0.568057,17427.544474,-0.225472,-0.209744,23.379624,148325.045335,148325.045335

In [12]:
# Find the start indices for each amino acid and ensure alphabetical order
amino_acids = sorted(data['mutation'].unique())
start_indices = [int(data[data['mutation'] == aa].index[0]) for aa in amino_acids]
data['mutation_site'] = data['mutation_site'].astype(str)
print(start_indices)

[0, 183, 370, 556, 745, 926, 1106, 1300, 1488, 1675, 1857, 2052, 2230, 2414, 2603, 2789, 2969, 3153, 3332, 3525]

In [30]:
df_var.head()

,seq_id,rmsd,tm_score,sasa,avg_hydro,plddt,local_net_energy,global_net_energy,iptm_ptm,iptm,...,Polar,Hydrophobhic,Charged,contact_pairs,sc,hb,sb,int_solv_en,int_area,pi_score
0,eta_variant,2.709862,0.987794,10204.940348,0.423810,0.742525,0.140996,158042.327798,0.024063,0.023774,...,0.547893,0.200280,0.572,0.028926,0.415033,0.232558,0.153846,0.780083,0.329772,0.296089
1,iota_variant,2.707459,0.987811,10220.165268,0.423810,0.761306,0.917536,185215.896651,0.035700,0.036645,...,0.704981,0.221289,0.632,0.086777,0.472222,0.162791,0.000000,0.638411,0.308965,0.173184
2,alpha_variant,2.239784,0.987749,10191.032125,0.284921,0.712454,0.106250,156826.459284,0.044419,0.043586,...,0.574713,0.326331,0.534,0.123967,0.351307,0.186047,0.000000,0.359810,0.391764,0.142458
3,epsilon_variant,2.985674,0.987082,10160.627795,0.690476,0.739846,0.305124,163785.673177,0.038174,0.041263,...,0.773946,0.446779,0.170,0.384298,0.158497,0.465116,0.076923,0.055720,0.562465,0.631285

1,196,391,586,781,976,1171,1366,1561,1756,1951,2146,2341,2536,2731,2926,3121,3316,3511,3706,3901

In [49]:
# Function to plot RMSD
def plot_rmsd(data, y_column, plot_title, y_label, wildtype, save_path):
    plt.figure(figsize=(15, 8))  # Increase the figure size
    # plt.plot(data['mutation_site'], data[y_column], marker='o', markersize=1.5, linestyle='-', color='b', linewidth=0.5, label='Data')
    plt.plot(data['mutation_site'], data[y_column], marker='o', linestyle='None', markersize=1.5, color='b', linewidth=0.5, label='Data')
    
    plt.axhline(y=wildtype, color='r', linestyle='--', label='Wildtype')  # Add a horizontal line for the wildtype value
    plt.text(len(data['mutation_site']) - 1, wildtype, 'Wildtype', color='r', va='bottom', ha='left')

    # Highlight parameters
    highlight_indices = [3682, 2719, 1633]
    highlight_labels = ['Alpha', 'Epsilon', 'Eta/Iota']
    highlight_colors = ['red', 'green', 'orange']

    # Highlight the special points
    for i, idx in enumerate(highlight_indices):
        point_x = data['mutation_site'].iloc[idx]
        point_y = data[y_column].iloc[idx]
        plt.plot(point_x, point_y, marker='o', color=highlight_colors[i], linestyle='None')  # Use specific color
        plt.text(point_x, point_y, highlight_labels[i], fontsize=12, ha='right', weight='bold')  # Add label

    # Set labels and title
    plt.xlabel('Mutational Variants (Sorted)')
    plt.ylabel(f'{y_label}')
    plt.title(f'{plot_title} for 1-step Mutational Variants')

    # Adjust x-axis labels to show only the start of each amino acid
    plt.xticks(ticks=start_indices, labels=amino_acids, rotation=90, fontsize=8)
    
    # Display the plot
    plt.grid(True, which='both', linestyle='--', linewidth=0.5)
    plt.tight_layout()
    # Save the plot if save_path is provided
    if save_path:
        plt.savefig(save_path, format='png', dpi=300)
        print(f"Plot saved to {save_path}")

    plt.show()

In [50]:
title_list = ['Electrostatic Potential', 'IPTM PTM', 'IPTM', 'pDockQ_mpDockQ', 'Average Interface PAE', 'Average Interface PLDDT', 'Binding Energy', 'Number of Interface Residues', 'Polar', 'Hydrophobic', 'Charged', 'Contact Pairs', 'SC', 'HB', 'SB', 'Interface Solvation Energy', 'Interface Area', 'PI Score']

In [7]:
test_list = ['local_net_energy']

In [ ]:
complex_list = ['BDM', 'Shannon Entropy', 'LZW ratio']

In [ ]:
for i, column in enumerate(c_list):
    print(column)
    wild_type = df_ref[column].mean()
    save_path = f'/home/max/stayahead/analysis/plots/AF_scatter/AF_{title_list[i]}_plot.png'
    plot_rmsd(data, column, title_list[i], column, wild_type, save_path)

In [ ]:
y_column = 'local_net_energy'
plot_title = 'Electrostatic Potential'
y_label = 'Electrostatic Potential'
# wildtype = (df_ref[y_column].mean() - min) / (max - min)
wildtype = df_ref[y_column].mean()
plot_rmsd(data, y_column, plot_title, y_label, wildtype, save_path='/home/max/stayahead/analysis/scripts/AF_EP_plot.png')

Variant Scores Normalized
RMSD: 0.23770632763969754 0.36359668548110957 0.3170454620303818 0.316639885620306
TM_score: 0.33119388765452357 0.29381532467630367 0.3337210449798626 0.33470213092926077

In [46]:
data['bind'].mean()

7.758061660758113

In [2]:
os.cpu_count()

12

In [ ]:
# Function to plot RMSD
def plot_rmsd(data, alpha, epsilon, eta, iota):
    plt.figure(figsize=(15, 8))  # Increase the figure size
    plt.plot(data['mutation_site'], data['avg_hydro'], marker='o', markersize=1.5, linestyle='-', color='b', linewidth=0.5)
    
    # Add the horizontal threshold lines and labels with different colors
    plt.axhline(y=alpha, color='r', linestyle='--', label='Alpha Variant')
    plt.axhline(y=epsilon, color='g', linestyle='--', label='Epsilon Variant')
    plt.axhline(y=eta, color='orange', linestyle='--', label='Eta Variant')
    plt.axhline(y=iota, color='purple', linestyle='--', label='Iota Variant')

    plt.text(len(data['mutation_site']) - 1, alpha, 'Alpha', color='r', va='bottom', ha='left')
    plt.text(len(data['mutation_site']) - 1, epsilon, 'Epsilon', color='g', va='bottom', ha='left')
    plt.text(len(data['mutation_site']) - 1, eta, 'Eta', color='orange', va='bottom', ha='left')
    plt.text(len(data['mutation_site']) - 1, iota, 'Iota', color='purple', va='bottom', ha='left')

    # Set labels and title
    plt.xlabel('Mutational Variants (Sorted)')
    plt.ylabel('Average Hydrophobicity')
    plt.title('Average Hydrophobicity for 1-step Mutational Variants')
    
    # Adjust x-axis labels to show only the start of each amino acid
    plt.xticks(ticks=start_indices, labels=amino_acids, rotation=90, fontsize=8)
    
    # Add grid lines
    plt.grid(True, which='both', linestyle='--', linewidth=0.5)
    
    # Display the plot
    plt.tight_layout()
    plt.show()

In [26]:
# Sort the data by 'wildtype' and 'site'
data_sorted = df_1h_20_bits.sort_values(by=['mutation', 'site'])

# Create a new column for combined mutation and site
data_sorted['mutation_site'] = data_sorted['mutation'] + data_sorted['site'].astype(str)

In [18]:
data_sorted.head(1)

,seq_id,wildtype,site,mutation,rmsd,tm_score,sasa,avg_hydro,total_hydro,plddt,...,BDM,Shannon Entropy,LZW ratio,bind,delta_bind,expr,delta_expr,confidence_bind,confidence_expr,mutation_site
3662,T1A,T,1,A,3.997568,0.987932,10110.87034,-0.237868,-0.210769,93.834862,...,4734.139316,6.75986,0.820513,8.70879,-0.02454,10.0111,-0.17363,-0.788544,-1.079032,A1

In [2]:
df_af = pd.read_csv('/Users/maxvandenboom/stayahead/analysis/datasets/current/AF_1step_pred_wuhan_v1_b2b_parse.csv')
df_esm = pd.read_csv('/Users/maxvandenboom/stayahead/analysis/datasets/current/ESM_1step_pred_wuhan_v1_b2b_03-07.csv')

In [5]:
mutations = sorted(data_sorted['mutation'].unique())
sites = np.arange(1, 196)  # Since your site starts at 1 and ends at 195

# Create mesh grids for mutations and sites
mutation_indices, site_indices = np.meshgrid(mutations, sites, indexing='ij')

# Prepare a grid to hold the binding kinetics data
bind_grid = np.zeros_like(mutation_indices, dtype=float)

# Populate the bind grid with your data
for i, mut in enumerate(mutations):
    for j, site in enumerate(sites):
        # Filter data for each mutation and site
        filter_mask = (data_sorted['mutation'] == mut) & (data_sorted['site'] == site)
        if any(filter_mask):
            bind_grid[i, j] = data_sorted.loc[filter_mask, 'bind'].values[0]

In [ ]:
# Create the 3D plot
fig = go.Figure(data=[go.Scatter3d(
    x=data_sorted['mutation_site'],
    y=data_sorted['Shannon Entropy'],
    z=data_sorted['bind'],
    mode='markers',
    marker=dict(
        size=5,
        color=data_sorted['bind'],  # Set color to bind values
        colorscale='Viridis',     # Choose a colorscale
        opacity=0.8
    )
)])

# Set the title and axis labels
fig.update_layout(
    title='3D Scatter Plot of Bind vs Mutation Site and Shannon Entropy',
    scene=dict(
        xaxis=dict(
            title='Mutation Site',
            tickvals=start_indices,
            ticktext=amino_acids,
            tickangle=90,
            tickfont=dict(size=8)
        ),
        yaxis_title='Shannon Entropy',
        zaxis_title='Bind'
    ),
width=1200,  # Set the width of the plot
height=800  # Set the height of the plot
)

# Show the plot
fig.show()